### ISSUE TITLE
MERGE_ENABLED causes application not to start

### ISSUE THREAD

**Issue by bmbouter** [rochacbruno/dynaconf#111]
Pulp uses dynaconf for [its configuration](https://docs.pulpproject.org/en/3.0/nightly/installation/configuration.html). Pulp's django webserver for example, that will start successfully w/ the django extension for Dynaconf.

However on the terminal when I: `export MERGE_ENABLED_FOR_DYNACONF=true` I get the following traceback upon starting the djagno webserver:

```
(pulp) [vagrant@pulp3 ~]$ pulp-manager runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe95e0e5a60>
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/pulp/lib64/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/pulp/lib64/python3.6/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/vagrant/.virtualenvs/pulp/lib64/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/vagrant/.virtualenvs/pulp/lib64/python3.6/site-packages/django/core/management/__init__.py", line 337, in execute
    autoreload.check_errors(django.setup)()
  File "/home/vagrant/.virtualenvs/pulp/lib64/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/.virtualenvs/pulp/lib64/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenvs/pulp/lib64/python3.6/site-packages/django/apps/registry.py", line 93, in populate
    "duplicates: %s" % app_config.label)
django.core.exceptions.ImproperlyConfigured: Application labels aren't unique, duplicates: admin
```

**Comment by adevore** [comment]
I've encountered something similar. I think I traced it to how LazySettings handles default values. Values are first set in the LazySettings constructor via `self._kwargs = kwargs`. Later, the default_loader function runs LazySettings.set(), which proceeds to merge each kwarg with itself.

**Comment by rochacbruno** [comment]
In progress on #135

**Comment by rochacbruno** [comment]
Hi @bmbouter 

The next release is going to take place next monday

`MERGE_ENABLED_FOR_DYNACONF` is being deprecated and not you should use what is described in #139 which is merging per variable.
