### ISSUE TITLE
[bug] In Python 3.4 and below inspect.stack() returns just a tuple in the list, not a list of named tuples

### ISSUE THREAD

**Issue by Jazzis18** [rochacbruno/dynaconf#212]
**Describe the bug**
In Python 3.4 and below `inspect.stack()` returns just a tuple in the list, not a list of named tuples. Only since version 3.5 does it return a list of named tuples.

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash

# example.py
# settings.ini

```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**settings.ini**
```ini
[default]
path = 'example.txt'
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**example.py**
```python
from dynaconf import settings

print(settings.PATH)
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
$ python example.py

Traceback (most recent call last):
  File "example.py", line 3, in <module>
    print(settings.PATH)
  File "C:\Python\Python34\lib\site-packages\dynaconf\base.py", line 93, in __getattr__
    self._setup()
  File "C:\Python\Python34\lib\site-packages\dynaconf\base.py", line 118, in _setup
    default_settings.reload()
  File "C:\Python\Python34\lib\site-packages\dynaconf\default_settings.py", line 74, in reload
    start_dotenv(*args, **kwargs)
  File "C:\Python\Python34\lib\site-packages\dynaconf\default_settings.py", line 61, in start_dotenv
    or _find_file(".env", project_root=root_path)
  File "C:\Python\Python34\lib\site-packages\dynaconf\utils\files.py", line 62, in find_file
    script_dir = os.path.dirname(os.path.abspath(inspect.stack()[-1].filename))
AttributeError: 'tuple' object has no attribute 'filename'
```

</details>

**Expected behavior**
```python
from dynaconf import settings

print(settings.PATH)
# 'example.txt'
```

**Debug output**

<details>
<summary> Debug Output </summary>

```bash

export `DEBUG_LEVEL_FOR_DYNACONF=DEBUG` reproduce your problem and paste the output here
2019-08-26:16:46:23,988 DEBUG    [default_settings.py:55 - start_dotenv] Starting Dynaconf Dotenv Base
2019-08-26:16:46:23,989 DEBUG    [files.py:57 - find_file] No root_path for .env
Traceback (most recent call last):
  File "example.py", line 3, in <module>
    print(settings.PATH)
  File "C:\Python\Python34\lib\site-packages\dynaconf\base.py", line 93, in __getattr__
    self._setup()
  File "C:\Python\Python34\lib\site-packages\dynaconf\base.py", line 118, in _setup
    default_settings.reload()
  File "C:\Python\Python34\lib\site-packages\dynaconf\default_settings.py", line 74, in reload
    start_dotenv(*args, **kwargs)
  File "C:\Python\Python34\lib\site-packages\dynaconf\default_settings.py", line 61, in start_dotenv
    or _find_file(".env", project_root=root_path)
  File "C:\Python\Python34\lib\site-packages\dynaconf\utils\files.py", line 62, in find_file
    script_dir = os.path.dirname(os.path.abspath(inspect.stack()[-1].filename))
AttributeError: 'tuple' object has no attribute 'filename'
```

</details>

**Environment (please complete the following information):**
 - OS: Windows 8.1
 - Dynaconf Version 2.0.4
 - Python Version 3.4.3

**Comment by Jazzis18** [comment]
I'm the same guy who just still uses Python 3.4 and has not yet updated. I think this is a great reason to finally do it :)
