### ISSUE TITLE
[bug] Exception when getting non existing dotted keys with default value

### ISSUE THREAD

**Issue by sebbegg** [rochacbruno/dynaconf#251]
**Describe the bug**
Using settings.get(key, default) with a non-existing key - depending on the default value - produces an exception.
Am I missing something obvious?

**To Reproduce**

1. Having the following folder structure

- app.py
- config.py

2. Having the following config files:
- config.py 

3. Having the following app code:

<details>
<summary> Code </summary>

**app.py**
```python
from dynaconf import settings as s

s.load_file("config.py")

print("As dict:")
print(s.as_dict())

print("Existing key:", s.get("foo.bar"))

print("With 0 as default:", s.get("non.existing.key", 0))

print("With list as default:", s.get("non.existing.key", [1, 2, 3]))

```

**config.py**
```python
FOO = {
  "bar": "hello"
}
```

</details>

4. Executing under the following environment

```bash

$ python
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin

$ pip freeze
certifi==2019.9.11
chardet==3.0.4
Click==7.0
configobj==5.0.6
dynaconf==2.2.0
entrypoints==0.3
flake8==3.7.8
hvac==0.9.5
idna==2.8
mccabe==0.6.1
pycodestyle==2.5.0
pyflakes==2.1.1
python-box==3.4.5
python-dotenv==0.10.3
PyYAML==5.1.2
redis==3.3.11
requests==2.22.0
six==1.12.0
toml==0.10.0
urllib3==1.25.6

$ python app.py
As dict:
{'FOO': {'bar': 'hello'}}
Existing key: hello
With 0 as default: 0
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    print("With list as default:", s.get("non.existing.key", [1, 2, 3]))
  File "/Users/me/Stuff/dynaconf/pyenv/lib/python3.7/site-packages/dynaconf/base.py", line 296, in get
    dotted_key=key, default=default, cast=cast, fresh=fresh
  File "/Users/me/Stuff/dynaconf/pyenv/lib/python3.7/site-packages/dynaconf/base.py", line 275, in _dotted_get
    return self._dotted_get(".".join(keys), default=default, **kwargs)
  File "/Users/me/Stuff/dynaconf/pyenv/lib/python3.7/site-packages/dynaconf/base.py", line 265, in _dotted_get
    result = self.get(name, default=default, **kwargs)
  File "/Users/me/Stuff/dynaconf/pyenv/lib/python3.7/site-packages/dynaconf/base.py", line 312, in get
    data = store.get(key, default)
AttributeError: 'BoxList' object has no attribute 'get'
```

**Expected behavior**
No exception and no dependency on the default value

**Environment (please complete the following information):**
 - OS: Linux/Ubuntu18.04 and MacOS 10.14.6
 - Dynaconf Version: 2.2.0/wheel

**Comment by Natureshadow** [comment]
When is a new release containing this bugfix planned ;)?

**Comment by rochacbruno** [comment]
@Natureshadow new release planned for tomorrow
