### ISSUE TITLE
cant use dynaconf in python 3.6.1

### ISSUE THREAD

**Issue by jianglijie** [rochacbruno/dynaconf#280]
I use 'pip install dynaconf' to install it on my mac.
It installed dynaconf-2.2.2 python-box-3.4.6 python-dotenv-0.10.3 toml-0.10.0
when I use ``` from dynaconf import settings ``` in my project. It shows
```
Traceback (most recent call last):
  File "run/tools/test.py", line 7, in <module>
    from dynaconf import settings
  File "/usr/local/var/pyenv/versions/3.6.1-virtual/lib/python3.6/site-packages/dynaconf/__init__.py", line 1, in <module>
    from dynaconf.base import LazySettings
  File "/usr/local/var/pyenv/versions/3.6.1-virtual/lib/python3.6/site-packages/dynaconf/base.py", line 7, in <module>
    from dynaconf import default_settings
  File "/usr/local/var/pyenv/versions/3.6.1-virtual/lib/python3.6/site-packages/dynaconf/default_settings.py", line 11, in <module>
    from dynaconf.utils.parse_conf import parse_conf_data
  File "/usr/local/var/pyenv/versions/3.6.1-virtual/lib/python3.6/site-packages/dynaconf/utils/parse_conf.py", line 5, in <module>
    from box import BoxKeyError
  File "/usr/local/var/pyenv/shims/box.py", line 3
    [ -n "$PYENV_DEBUG" ] && set -x
                      ^
SyntaxError: invalid syntax
```

**Comment by hilam** [comment]
Maybe your "/usr/local/var/pyenv/shims/box.py" is in a different version of box inside your virtualenv ("/usr/local/var/pyenv/versions/3.6.1-virtual/")?

**Comment by jianglijie** [comment]
@hilam I check the file "/usr/local/var/pyenv/shims/box.py" found Its not the python-box. It created by pyenv. Maybe dynaconf cant work with pyenv virtualenv on macos.

**Comment by rochacbruno** [comment]
@jianglijie so this an issue to be reported both to  @pyenv and @cdgriffith box

**Comment by rochacbruno** [comment]
This is a pyenv problem, which is creating a global ` box`  module and conflicting with python-box. pyenv should use some namespace to avoid it.
