### ISSUE TITLE
Default values do not seem to resolve correctly

### ISSUE THREAD

**Issue by stratosgear** [rochacbruno/dynaconf#323]
**Describe the bug**
Default values do not seem to resolve correctly

**To Reproduce**

settings.toml:
```
[default]
a = 100
b = "BB"

[default.namespace]
b = "Default namespace B"

[development]
a = 200

[development.namespace]
a = "DEV Namespace A"
```

The simplest python program of:

```
from dynaconf import settings

print(settings.A)
print(settings.B)
print(settings.NAMESPACE.A)
print(settings.NAMESPACE.B)
```

Gives me:

```
200       # Looks OK, defined in development
BB        # Looks OK, missing in development but defined in default
DEV Namespace A    # Looks OK, defined in the development.namespace section
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/data/projects/pkh/rapidxmm/repos/backend/backend/src/.venv/lib/python3.7/site-packages/dynaconf/utils/boxing.py", line 15, in __getattr__
    return super(DynaBox, self).__getattr__(n_item, *args, **kwargs)
  File "/mnt/data/projects/pkh/rapidxmm/repos/backend/backend/src/.venv/lib/python3.7/site-packages/box.py", line 525, in __getattr__
    raise BoxKeyError(str(err))
box.BoxKeyError: "'DynaBox' object has no attribute 'b'"
```

I was expecting the `settings.NAMESPACE.B` to be picked up from my `default.namespace` section, in the same manner that `settings.B` was picked from `default`, but it does not!

Am I missing a configuration option to turn on such a behavior, or is this indeed a bug?

Thanks!

**Comment by rochacbruno** [comment]
Dynaconf reads namespaces as isolated dictionaries and doesn't know if your intention is to merge or replace data on it.

so you need to explicitly mark the merge.

```toml
[default]
a = 100
b = "BB"

[default.namespace]
b = "Default namespace B"

[development]
a = 200

[development.namespace]
a = "DEV Namespace A"
dynaconf_merge = true
```

Or enable the global merge on settings object.
