### ISSUE TITLE
[bug] Django extension incompatible with DJDT

### ISSUE THREAD

**Issue by wengole** [rochacbruno/dynaconf#382]
**Describe the bug**
Django Debug Toolbar calls `settings.is_overridden()` which results in `'Settings' object has no attribute 'IS_OVERRIDDEN'`

**To Reproduce**

1. Start new django project and add [django debug toolbar](https://django-debug-toolbar.readthedocs.io/en/latest/installation.html) version 2.2
2. Add dynaconf to settings.py as per instructions:
```python
# HERE STARTS DYNACONF EXTENSION LOAD (Keep at the very bottom of settings.py)
# Read more at https://dynaconf.readthedocs.io/en/latest/guides/django.html
import dynaconf  # noqa

settings = dynaconf.DjangoDynaconf(__name__, environments=True, load_dotenv=True)  # noqa
# HERE ENDS DYNACONF EXTENSION LOAD (No more code below this line)
```
3. Start the development server `python manage.py runserver`

**Expected behavior**
The Django development server to start-up with no errors

**Environment (please complete the following information):**
 - OS: Linux
 - Dynaconf 3.0.0

**Comment by wengole** [comment]
Full traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ben/.virtualenvs/ddp_api/lib/python3.8/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/ben/.virtualenvs/ddp_api/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/ben/.virtualenvs/ddp_api/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = self._run_checks(
  File "/home/ben/.virtualenvs/ddp_api/lib/python3.8/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/ben/.virtualenvs/ddp_api/lib/python3.8/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/ben/.virtualenvs/ddp_api/lib/python3.8/site-packages/debug_toolbar/apps.py", line 25, in check_middleware
    if settings.is_overridden("MIDDLEWARE_CLASSES"):
  File "/home/ben/.virtualenvs/ddp_api/lib/python3.8/site-packages/dynaconf/utils/parse_conf.py", line 195, in evaluate
    value = f(settings, *args, **kwargs)
  File "/home/ben/.virtualenvs/ddp_api/lib/python3.8/site-packages/dynaconf/base.py", line 165, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'IS_OVERRIDDEN'```

**Comment by rochacbruno** [comment]
We need to change the `contrib/django` extension to extend the LazySettings and include that one method or route it to the Django implementation.
