### ISSUE TITLE
Multi env settings

### ISSUE THREAD

**Issue by dyens** [rochacbruno/dynaconf#447]
In 2.2.3 version of dynaconf i have:

.secrets.toml
```
[default]
a = 3

[development]
a = 3
```

main.py
```python
from dynaconf import settings

print(settings.A)
```
And its work fine

In 3.1.2 version I start using a new confg.py mechanism:

.config.py (generated by dynaconf cli)

```
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="DYNACONF",
    settings_files=['settings.toml', '.secrets.toml'],
)
```

main.py
```python
from config import settings

print(settings.A)
```
I have an error (previous main.py file works fine (from dynaconf import settings)):
```
> poetry run python main.py
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    print(settings.A)
  File "/home/dyens/.cache/pypoetry/virtualenvs/dyntest-bSb0oaYP-py3.7/lib64/python3.7/site-packages/dynaconf/base.py", line 164, in __getattr__
    value = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'A'
```

If i try to print:
```python
print(settings.to_dict())
```
I have:
```
{'DEFAULT': {'a': 3}, 'DEVELOPMENT': {'a': 3}}
```

What i missed in my new configuration?
Thank you!

**Comment by dyens** [comment]
Thank you!

Its works. Sorry for the silly question.
