### ISSUE TITLE
Add warning about merging default nested dicts to the docs [was] default's nested dictionaries doesn't work as expected

### ISSUE THREAD

**Issue by thiras** [rochacbruno/dynaconf#479]
**Describe the bug**
Any nested under the `[default]` ignored while `environments=True`

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash

.
├── README.rst
├── config.py
├── poetry.lock
├── pyproject.toml
└── settings.toml

```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**settings.toml**
```toml
[default]
var = "string"

[default.nested]
var_n = "nested string"

[dev]
var = "dev string"

[dev.nested]
var_n2 = "this will be only var available"
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/config.py**
```python
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="DYNACONF",
    settings_files=['settings.toml', '.secrets.toml'],
    environments=True
)

print(settings.nested.var_n2)
print(settings.nested.var_n)
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
$ export ENV_FOR_DYNACONF=dev
$ python config.py 
this will be only var available
Traceback (most recent call last):
  File "config.py", line 14, in <module>
    print(settings.nested.var_n)
  File "/home/thiras/.cache/pypoetry/virtualenvs/dynaconf-test-fRv91C7R-py3.8/lib/python3.8/site-packages/dynaconf/utils/boxing.py", line 15, in evaluate
    value = f(dynabox, item, *args, **kwargs)
  File "/home/thiras/.cache/pypoetry/virtualenvs/dynaconf-test-fRv91C7R-py3.8/lib/python3.8/site-packages/dynaconf/utils/boxing.py", line 38, in __getattr__
    return super(DynaBox, self).__getattr__(n_item, *args, **kwargs)
  File "/home/thiras/.cache/pypoetry/virtualenvs/dynaconf-test-fRv91C7R-py3.8/lib/python3.8/site-packages/dynaconf/vendor/box/box.py", line 177, in __getattr__
    raise BoxKeyError(str(E)) from _A
dynaconf.vendor.box.exceptions.BoxKeyError: "'DynaBox' object has no attribute 'VAR_N'"
```

</details>

**Expected behavior**
I would like to see default's nested dictionaries behave the same as their parents, [default].

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Dynaconf Version 3.1.2

**Comment by mafeko** [comment]
**Describe the bug**
I faced the same issue in a little more complex setup but with the same error

**To Reproduce**
Steps to reproduce the behaviour:

1. Having the following folder structure



<details>
<summary> Project structure </summary>

```bash
.
├── config.py
├── poetry.lock
├── pyproject.toml
└── settings.toml
```
</details>

2. Having the following config files:
<details>
<summary> Config files </summary>

**./settings.yaml**
```yaml
--- 

default:
  var: 1
  var1: "@format {this.outside}.var1"
  sub:
    var2: "@format {this.var1}.var2"
  
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**./config.py**
```python
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="DYNACONF", settings_files=["settings.yaml"], environments=True,
)


print(settings.var)
print(settings.var1)
print(settings.sub.var2)

```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
export DYNACONF_OUTSIDE=abc; python config.py

1
abc.var1
Traceback (most recent call last):
  File "config.py", line 10, in <module>
    print(settings.sub.var2)
  File "/Users/kop7pl/Library/Caches/pypoetry/virtualenvs/dynaconf-test-KR0mwqMm-py3.8/lib/python3.8/site-packages/dynaconf/utils/boxing.py", line 15, in evaluate
    value = f(dynabox, item, *args, **kwargs)
  File "/Users/kop7pl/Library/Caches/pypoetry/virtualenvs/dynaconf-test-KR0mwqMm-py3.8/lib/python3.8/site-packages/dynaconf/utils/boxing.py", line 38, in __getattr__
    return super(DynaBox, self).__getattr__(n_item, *args, **kwargs)
  File "/Users/kop7pl/Library/Caches/pypoetry/virtualenvs/dynaconf-test-KR0mwqMm-py3.8/lib/python3.8/site-packages/dynaconf/vendor/box/box.py", line 177, in __getattr__
    raise BoxKeyError(str(E)) from _A
dynaconf.vendor.box.exceptions.BoxKeyError: "'Settings' object has no attribute 'var1'"
```
</details>

**Expected behavior**
Expected output would be
```bash
1
abc.var1
abc.var1.var2
```

**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - Dynaconf Version **3.1.2**

**Comment by rochacbruno** [comment]
I suspect this is not a bug

```toml
[default]
var = "string"

[default.nested]
var_n = "nested string"

[dev]
var = "dev string"

[dev.nested]
var_n2 = "this will be only var available"
```

the above is missing `dynaconf_merge` which is opt-in

```toml
[default]
var = "string"

[default.nested]
var_n = "nested string"

[dev]
var = "dev string"

[dev.nested]
dynaconf_merge = true
var_n2 = "this will be only var available"
```

Should we default to always `merge` when the environment == `default_env` ?
