### ISSUE TITLE
[bug] - Dynaconf stop list variables and does not recognize develop variables in my env

### ISSUE THREAD

**Issue by jonatasoli** [rochacbruno/dynaconf#556]
Dynaconf dont list variables and thrown a error validation.

* I change my config from mac +zsh to manjaro + fish
* I run my venv
* I run dynaconf -i config.settings list

1. Having the following folder structure

> tree                                                  09:10:07
.
├── alembic
│   ├── env.py
│   ├── __pycache__
│   │   └── env.cpython-39.pyc
│   ├── README
│   ├── script.py.mako
│   └── versions
├── alembic.ini
├── api
│   ├── api_v1
│   │   └── __init__.py
│   ├── deps.py
│   ├── __init__.py
│   └── tests
│       ├── __init__.py
│       ├── test_celery.py
│       ├── test_items.py
│       ├── test_login.py
│       └── test_users.py
├── backend_pre_start.py
├── celeryworker_pre_start.py
├── config.py
├── config.py.old
├── conftest.py
├── connections
│   ├── fetcher.py
│   └── __init__.py
├── constants
│   ├── core.py
│   ├── __init__.py
│   └── shopping_cart_checkout.py
├── crud
│   ├── base.py
│   └── tests
│       ├── __init__.py
│       ├── test_item.py
│       └── test_user.py
├── db
│   ├── base_class.py
│   ├── base.py
│   ├── __init__.py
│   └── __pycache__
│       ├── base_class.cpython-39.pyc
│       ├── base.cpython-39.pyc
│       └── __init__.cpython-39.pyc
├── ext
│   ├── celery_app.py
│   ├── config.py
│   ├── database.py
│   ├── __init__.py
│   └── security.py
├── init_db.py
├── initial_data.py
├── __init__.py
├── main.py
├── models
├── __pycache__
│   └── config.cpython-39.pyc
├── schemas
├── settings.toml
├── test.py
├── tests
│   ├── __init__.py
│   └── utils
│       ├── __init__.py
│       ├── item.py
│       ├── user.py
│       └── utils.py
├── tests_pre_start.py
├── utils.py
└── worker.py

2. Having the following config files:

The dynaconf run in app folder and settings.toml and .secrets.toml staying in app folder
**/app/.secrets.toml**
```toml
[development]
# Postgres
POSTGRES_SERVER=172.15.0.2
POSTGRES_USER=user
POSTGRES_PASSWORD=pass
POSTGRES_DB=mydb
```

and

**/app/settings.toml**
```toml
[default]
STACK_NAME="paymentgateway-com-br"

BACKEND_CORS_ORIGINS=["http://dev.domain.com"]
PROJECT_NAME="Microservice Gateway"
SECRET_KEY="dc24d995bf6c"
FIRST_SUPERUSER="email@email.com.br"
FIRST_SUPERUSER_PASSWORD="123"
SMTP_TLS=true
SMTP_PORT=587
SMTP_HOST=""
SMTP_USER=""
SMTP_PASSWORD=""
EMAILS_FROM_EMAIL="email@email.com"

USERS_OPEN_REGISTRATION=false
SENTRY_DSN=""
API_V1_STR="/payment-api/v1"
# 60 minutes * 24 hours * 8 days = 8 days
ACCESS_TOKEN_EXPIRE_MINUTES=11520

[development]
DOMAIN="localhost"
TRAEFIK_PUBLIC_NETWORK="traefik-public"
TRAEFIK_TAG="paymentgateway.app.com.br"
TRAEFIK_PUBLIC_TAG="traefik-public"

DOCKER_IMAGE_BACKEND="docker"

BACKEND_CORS_ORIGINS=["http://localhost", "https://localhost"]

# Postgres
SQLALCHEMY_DATABASE_URI="..."
```

3. Having the following app code:
```python
from typing import Any

from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from dynaconf import settings

from loguru import logger


def get_engine():
    SQLALCHEMY_DATABASE_URL = settings.SQLALCHEMY_DATABASE_URI

    engine = create_engine(
        SQLALCHEMY_DATABASE_URL,
    )
    return engine

def get_session():
    _engine = get_engine()
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=_engine)
    return SessionLocal

```

**/app/main.py**
```python
from fastapi import FastAPI
from starlette.middleware.cors import CORSMiddleware

from api.api_v1.api import api_router
from dynaconf import settings

import logging
import sys
from loguru import logger

app = FastAPI(
    title=settings.PROJECT_NAME,
    openapi_url=f"{settings.API_V1_STR}/openapi.json",
    docs_url="/payment-api",
    redoc_url=None
)

if settings.BACKEND_CORS_ORIGINS:
    app.add_middleware(
        CORSMiddleware,
        allow_origins=[str(origin) for origin in settings.BACKEND_CORS_ORIGINS],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

app.include_router(api_router, prefix=settings.API_V1_STR)

```

4. Executing under the following environment
<development>

```fish
$ cd app
$ dynaconf -i config.settings list
```

</details>

**Expected behavior**
List all variables settings

**Environment (please complete the following information):**
 - OS: Manjaro BSPWN 20.0.1
 - Dynaconf Version 3.1.2 and 3.1.4
 - Frameworks in use (FastAPI - 0.61.2)

**Additional context**
Error:
```
> dynaconf -i config.settings list                      09:06:22
Traceback (most recent call last):
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/vendor/toml/decoder.py", line 253, in loads
    try:n=K.load_line(C,G,T,P)
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/vendor/toml/decoder.py", line 355, in load_line
    if P==A[-1]:raise ValueError('Invalid date or number')
ValueError: Invalid date or number

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/bin/dynaconf", line 8, in <module>
    sys.exit(main())
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 221, in __call__
    def __call__(A,*B,**C):return A.main(*B,**C)
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 205, in main
    H=E.invoke(F)
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 345, in invoke
    with C:return F(C.command.invoke(C))
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 288, in invoke
    if A.callback is not _A:return ctx.invoke(A.callback,**ctx.params)
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 170, in invoke
    with G:return A(*B,**E)
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/cli.py", line 442, in _list
    cur_env = settings.current_env.lower()
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/base.py", line 145, in __getattr__
    self._setup()
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/base.py", line 195, in _setup
    self._wrapped = Settings(
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/base.py", line 259, in __init__
    self.execute_loaders()
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/base.py", line 990, in execute_loaders
    settings_loader(
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/loaders/__init__.py", line 126, in settings_loader
    loader["loader"].load(
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/loaders/toml_loader.py", line 31, in load
    loader.load(filename=filename, key=key, silent=silent)
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/loaders/base.py", line 62, in load
    source_data = self.get_source_data(files)
  File "/home/jonatas/workspace/microservice-payment-gateway/.ve
nv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/loaders/base.py", line 83, in get_source_data
    content = self.file_reader(open_file)
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/vendor/toml/decoder.py", line 83, in load
    try:return loads(f.read(),B,A)
  File "/home/jonatas/workspace/microservice-payment-gateway/.venv/app-payment-gateway-yLI0xW6Q-py3.9/lib/python3.9/site-packages/dynaconf/vendor/toml/decoder.py", line 254, in loads
    except ValueError as Y:raise TomlDecodeError(str(Y),I,N)
dynaconf.vendor.toml.decoder.TomlDecodeError: Invalid date or number (line 3 column 1 char 25)
```

**Comment by rochacbruno** [comment]
Toml expects string to be quoted

```diff
-[development]
-# Postgres
-POSTGRES_SERVER=172.15.0.2
-POSTGRES_USER=user
-POSTGRES_PASSWORD=pass
-POSTGRES_DB=mydb
+[development]
+# Postgres
+POSTGRES_SERVER = "172.15.0.2"
+POSTGRES_USER = "user"
+POSTGRES_PASSWORD = "pass"
+POSTGRES_DB = "mydb"
```

**Comment by rochacbruno** [comment]
Also:

Since 3.0.0 it is no more recommended to do `from dynaconf import settings`

The recommendation now is to create your own config isntance, in the root of your project, for example:

`config.py`
```py
from dynaconf import Dynaconf
settings = Dynaconf(
   settings_files=["settings.toml", ".secrets.toml"],
   environments=True
)
```

then in your `app/main.py`

```py
from config import settings
```

and then you do this ^ import on every place you need the settings.

**Comment by rochacbruno** [comment]
If you want to keep using `from dynaconf import settings` it is ok for now, (on 4.0.0 it will be removed)

then the command line should be:

```
dynaconf -i dynaconf.settings list
```

Let me know if the error still happens and thanks for reporting.

**Comment by jonatasoli** [comment]
I was not really paying attention to the detail of the variables not having quotes.
I appreciate the help, this on the roadmap here change these settings :)
Thank you again!
