### ISSUE TITLE
Using dynaconf with hashicorp vault

### ISSUE THREAD

**Issue by Uehara96** [rochacbruno/dynaconf#624]
I'm trying to use a vault server to store environment variables.
My configuration files on root directory:
config.py
```
from dynaconf import Dynaconf
settings = Dynaconf(
    environments=True,
    vault={'url': 'http://<vault-ip>:8200', 'token': '<root-token>' },
    vault_enabled=True, )
```

.env
```
ENV_FOR_DYNACONF=development
VAULT_ENABLED_FOR_DYNACONF=true
VAULT_URL_FOR_DYNACONF="http://<vault-ip>:8200/"

# Specify the secrets engine for kv, default is 1
VAULT_KV_VERSION_FOR_DYNACONF=2

# Authenticate with token https://www.vaultproject.io/docs/auth/token
VAULT_TOKEN_FOR_DYNACONF="<vault-root-token>"

# Authenticate with AppRole https://www.vaultproject.io/docs/auth/approle
#VAULT_ROLE_ID_FOR_DYNACONF="<vault-role-id>"
#VAULT_SECRET_ID_FOR_DYNACONF="<vault-secret-id>"

# Authenticate with AWS IAM https://www.vaultproject.io/docs/auth/aws
# The IAM Credentials can be retrieved from the standard providers: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html
# VAULT_AUTH_WITH_IAM_FOR_DYNACONF=True
# VAULT_AUTH_ROLE_FOR_DYNACONF="dynaconf"

# Authenticate with root token
#VAULT_ROOT_TOKEN_FOR_DYNACONF="<vault-root-token>"
```

I've tried to authenticate with the root token and approle from vault.

On the vault server, I have the following secrets:
<img width="297" alt="vault secrets" src="https://user-images.githubusercontent.com/42937807/126806503-cb119943-1c3b-426d-a2a3-add70b19952e.png">

Whenever I try to write a secret on default/development environment:
`dynaconf -i config.settings write vault -s password=123456`
I get:
```
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hvac/v1/__init__.py:114: DeprecationWarning: Call to deprecated property 'kv'. This property will be removed in version '0.9.0' Please use the 'kv' property on the 'Client.secrets' attribute moving forward.
  return utils.getattr_with_deprecated_properties(
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/dynaconf", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 221, in __call__
    def __call__(A,*B,**C):return A.main(*B,**C)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 205, in main
    H=E.invoke(F)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 345, in invoke
    with C:return F(C.command.invoke(C))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 288, in invoke
    if A.callback is not _A:return ctx.invoke(A.callback,**ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dynaconf/vendor/click/core.py", line 170, in invoke
    with G:return A(*B,**E)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dynaconf/cli.py", line 615, in write
    loader.write(settings, _vars, **_secrets)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/dynaconf/loaders/vault_loader.py", line 143, in write
    client.secrets.kv.create_or_update_secret(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hvac/api/secrets_engines/kv_v2.py", line 138, in create_or_update_secret
    return self._adapter.post(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hvac/adapters.py", line 121, in post
    return self.request("post", url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hvac/adapters.py", line 356, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hvac/adapters.py", line 322, in request
    utils.raise_for_error(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/hvac/utils.py", line 43, in raise_for_error
    raise exceptions.InvalidPath(message, errors=errors, method=method, url=url)
hvac.exceptions.InvalidPath: {"request_id":"ded59657-8182-dc9f-de47-4fdd58f2388f","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv put' for this operation."],"auth":null}, on post http://<vault-ip>:8200/v1/secret/data/dynaconf/default
```

dynaconf version: 3.1.4
python version: 3.9.4
hvac version: 0.11.0

It seems to have a problem with vault kv version 2. Has anyone configured this successfully?

**Comment by Uehara96** [comment]
I've changed the path of the secret kv to secret/ and the data was successfully written to vault!

**Comment by rochacbruno** [comment]
I am reopening as looks like we still need the fix to that 'kv' deprecation.
