### ISSUE TITLE
[bug]  UnicodeEncodeError upon dynaconf init

### ISSUE THREAD

**Issue by ebenh** [rochacbruno/dynaconf#664]
**Describe the bug**

`dynaconf init -f yaml` results in a `UnicodeEncodeError `

**To Reproduce**

1. `git clone -b dynaconf https://github.com/ebenh/django-flex-user.git`
2. `py -m pipenv install --dev`
3. `py -m pipenv shell`
4. `export DJANGO_SETTINGS_MODULE=test_project.settings`
5. `dynaconf init -f yaml`

**Error Message**

```
Traceback (most recent call last):
  File "C:\Users\eben\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\eben\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\eben\.virtualenvs\django-flex-user-ab_cVlY8\Scripts\dynaconf.exe\__main__.py", line 7, in <module>
  File "c:\users\eben\.virtualenvs\django-flex-user-ab_cvly8\lib\site-packages\dynaconf\vendor\click\core.py", line 221, in __call__
    def __call__(A,*B,**C):return A.main(*B,**C)
  File "c:\users\eben\.virtualenvs\django-flex-user-ab_cvly8\lib\site-packages\dynaconf\vendor\click\core.py", line 205, in main
    H=E.invoke(F)
  File "c:\users\eben\.virtualenvs\django-flex-user-ab_cvly8\lib\site-packages\dynaconf\vendor\click\core.py", line 345, in invoke
    with C:return F(C.command.invoke(C))
  File "c:\users\eben\.virtualenvs\django-flex-user-ab_cvly8\lib\site-packages\dynaconf\vendor\click\core.py", line 288, in invoke
    if A.callback is not _A:return ctx.invoke(A.callback,**ctx.params)
  File "c:\users\eben\.virtualenvs\django-flex-user-ab_cvly8\lib\site-packages\dynaconf\vendor\click\core.py", line 170, in invoke
    with G:return A(*B,**E)
  File "c:\users\eben\.virtualenvs\django-flex-user-ab_cvly8\lib\site-packages\dynaconf\vendor\click\decorators.py", line 21, in A
    def A(*A,**B):return f(get_current_context(),*A,**B)
  File "c:\users\eben\.virtualenvs\django-flex-user-ab_cvly8\lib\site-packages\dynaconf\cli.py", line 257, in init
    click.echo("\u2699\ufe0f  Configuring your Dynaconf environment")
  File "c:\users\eben\.virtualenvs\django-flex-user-ab_cvly8\lib\site-packages\dynaconf\vendor\click\utils.py", line 82, in echo
    if A:B.write(A)
  File "C:\Users\eben\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-1: character maps to <undefined>

```

**Comment by endersonmenezes** [comment]
I'm trying to reproduce this, and will go study to correct.

**Comment by endersonmenezes** [comment]
![image](https://user-images.githubusercontent.com/11020807/136447731-38c1d50e-b669-4903-ac8e-e7fd3a23f673.png)

This issue seems to have been fixed in latest Windows updates. https://github.com/microsoft/terminal/issues/190

I'm researching if this fix is only in Newer Builds. (I'm using Windows 11), and seeing how we can work around to not break the execution in older builds.

**Comment by endersonmenezes** [comment]
@ebenh you are using python 37, 38 or 39?
