### ISSUE TITLE
pyinstaller ModuleNotFoundError

### ISSUE THREAD

**Issue by PhE** [rochacbruno/dynaconf#68]
I get this error when I run an exe generated from pyinstaller : 
```
>dummy.exe
Hello World !!!
Traceback (most recent call last):
  File "dummy.py", line 4, in <module>
  File "site-packages\dynaconf\base.py", line 87, in __getattr__
  File "site-packages\dynaconf\base.py", line 113, in _setup
  File "site-packages\dynaconf\base.py", line 166, in __init__
  File "site-packages\dynaconf\base.py", line 575, in execute_loaders
  File "site-packages\dynaconf\base.py", line 550, in loaders
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dynaconf.loaders.env_loader'
[3256] Failed to execute script dummy
```

Here is my source script dummy.py : 
```python
import dynaconf

print('Hello World !!!')
print(dynaconf.settings.var1)
```

I use the latest 64 bits anaconda on a windows 7 64 bits and :
```shell
pip.exe install pyinstaller==3.3.*
pip.exe install pyyaml==3.12.* dynaconf[yaml]==1.0.*
```

I try to build a folder or a single exe with pyinstaller (both give the same error) : 
`pyinstaller.exe dummy.py`
or
`pyinstaller.exe --onefile dummy.py`

**Comment by rochacbruno** [comment]
Hi, I never tested in windows thanks for reporting, I may need help to test it on windows and find the solution.

**Comment by PhE** [comment]
Found a workaround :
```
pyinstaller.exe --onefile --hidden-import=dynaconf.loaders.env_loader
```

**Comment by victorpb** [comment]
@PhE 
if you run out of pyinstaller does it work?

**Comment by rochacbruno** [comment]
I want to solve it for the next release but I dont know how to reproduce and get the root cause

**Comment by PhE** [comment]
@victorpb  : yes it works out of pyinstaller on windows

@rochacbruno  : don't know how to solve it too. Since it works with the hidden-import workaround, I will close the issue

**Comment by pvmm** [comment]
The correct way to fix this is by creating a hook file for Pyinstaller. [Here](https://github.com/pyinstaller/pyinstaller/pull/3641) is my proposal.
