### ISSUE TITLE
Exception is thrown if dynaconf_hooks.py not exists

### ISSUE THREAD

**Issue by johan-westin-private** [rochacbruno/dynaconf#724]
Hi,

Thanks for a useful package!

When try to upgrade from 3.1.5 to 3.1.7 today, I got an Exception since a dynaconf_hooks.py did not exists.

Q: Would't it be better of the dynaconf_hooks.py file(s) are optional and be given to y_loader.import_from_filename(...) only when exist?

Best reagrds,
Johan Westin

**Comment by rochacbruno** [comment]
Hi @johan-westin-private that file must be optional, never required, if it being required it is a bug.

CAn you provide more information on the steps to reproduce it?

**Comment by johan-westin-private** [comment]
Hi,

This is the stack trace:

/home/johan/project/envs/py37_dev/bin/python -m unittest discover --pattern *_test.py --start-directory ./src/main/python --top-level-directory src/main/python --verbose
dler (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: dler (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: dler
Traceback (most recent call last):
  File "/opt/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/unittest/loader.py", line 468, in _find_test_path
    package = self._get_module_from_name(name)
  File "/opt/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/home/johan/project/src/main/python/dler/__init__.py", line 293, in <module>
    from .logging.logging_configurator import _patch_logging  # do not move this
  File "/home/johan/project/src/main/python/dler/logging/__init__.py", line 29, in <module>
    class JobIdHostnameLoggingFilter(HostnameLoggingFilter):
  File "/home/johan/project/src/main/python/dler/logging/__init__.py", line 30, in JobIdHostnameLoggingFilter
    clusterJobId = os.getenv(MyAttributeEnum.JOB_ID_ENV_VAR_NAME.dynamic, -1)
  File "/home/johan/project/src/main/python/dler/config/attribute.py", line 78, in dynamic
    value_from_config = settings.get(obj.attr_name, default=obj.attr_default)
  File "/home/johan/project/envs/py37_dev/lib/python3.7/site-packages/dynaconf/base.py", line 113, in __getattr__
    self._setup()
  File "/home/johan/project/envs/py37_dev/lib/python3.7/site-packages/dynaconf/base.py", line 164, in _setup
    settings_module=settings_module, **self._kwargs
  File "/home/johan/project/envs/py37_dev/lib/python3.7/site-packages/dynaconf/base.py", line 233, in __init__
    self.execute_loaders()
  File "/home/johan/project/envs/py37_dev/lib/python3.7/site-packages/dynaconf/base.py", line 980, in execute_loaders
    execute_hooks("post", self, env, silent=silent, key=key)
  File "/home/johan/project/envs/py37_dev/lib/python3.7/site-packages/dynaconf/loaders/__init__.py", line 126, in execute_hooks
    key=key,
  File "/home/johan/project/envs/py37_dev/lib/python3.7/site-packages/dynaconf/loaders/__init__.py", line 72, in _run_hook_module
    raise hook_module._error
  File "/home/johan/project/envs/py37_dev/lib/python3.7/site-packages/dynaconf/loaders/py_loader.py", line 113, in import_from_filename
    encoding=default_settings.ENCODING_FOR_DYNACONF,
FileNotFoundError: [Errno 2] py_loader: error loading file (No such file or directory /home/johan/project/etc/dler/dynaconf_hooks.py)
: ''


hook_file = os.path.join(os.path.dirname(loaded_file), "dynaconf_hooks.py")

# hook_file === '/home/johan/project/etc/dler/dynaconf_hooks.py'

When that is given to py_loader.import_from_filename(...), as filename, it execute

_find_file(filename) which return '' (empty string).

When '' is given to io.open(...) an Exception is raised, that dynaconf catch and translate to above FileNotFoundError.

Hope you can follow.

Best regards,
Johan Westin
