### ISSUE TITLE
Error when creating project within a Venv on ConfigObj()

### ISSUE THREAD

**Issue by tian2992** [rochacbruno/dynaconf#739]
**Describe the bug**
When creating a project i get an error on 
```
$ dynaconf init -f ini
...

    new = ConfigObj()
TypeError: 'NoneType' object is not callable
```

**To Reproduce**
Initalize virtual environment, i used venv version 20
pip install dynaconf
run dynaconf init -f ini

1. Executing

<details>
<summary> Traceback </summary>

```bash

Traceback (most recent call last):
  File "/mybasedir/v/bin/dynaconf", line 8, in <module>
    sys.exit(main())
  File /mybasedir/v/lib/python3.8/site-packages/dynaconf/vendor/click/core.py", line 221, in __call__
    def __call__(A,*B,**C):return A.main(*B,**C)
  File "/mybasedir/v/lib/python3.8/site-packages/dynaconf/vendor/click/core.py", line 205, in main
    H=E.invoke(F)
  File "/mybasedir//v/lib/python3.8/site-packages/dynaconf/vendor/click/core.py", line 345, in invoke
    with C:return F(C.command.invoke(C))
  File "/mybasedir//v/lib/python3.8/site-packages/dynaconf/vendor/click/core.py", line 288, in invoke
    if A.callback is not _A:return ctx.invoke(A.callback,**ctx.params)
  File "/mybasedir//v/lib/python3.8/site-packages/dynaconf/vendor/click/core.py", line 170, in invoke
    with G:return A(*B,**E)
  File "/mybasedir//v/lib/python3.8/site-packages/dynaconf/vendor/click/decorators.py", line 21, in A
    def A(*A,**B):return f(get_current_context(),*A,**B)
  File "/mybasedir//v/lib/python3.8/site-packages/dynaconf/cli.py", line 358, in init
    loader.write(settings_path, settings_data, merge=True)
  File "/mybasedir//v/lib/python3.8/site-packages/dynaconf/loaders/ini_loader.py", line 58, in write
    new = ConfigObj()
```
</details>

**Expected behavior**
not this.

**Environment (please complete the following information):**
 - OS: Linux
 - Dynaconf Version: 3.1.8 from pip

**Comment by rochacbruno** [comment]
can you try with `pip install dynaconf[ini]` ? or previously installing `pip install configobj`

**Comment by tian2992** [comment]
This did the trick. Could this please be documented at quickstart or in normal docs?

Thank you again!
